esbd2/atividade2/lists/urls.py
from django.urls import include, re_path
from lists import views

urlpatterns = [
    re_path(r'^new$', views.new_list, name='new_list'),
    re_path(r'^(\d+)/$', views.view_list, name='view_list'),
    re_path(r'^(\d+)/add_item$', views.add_item, name='add_item'),
]

esbd2/atividade2/trabalho_tdd/urls.py
from django.urls import include, re_path

from lists import views as list_views
from lists import urls as list_urls

urlpatterns = [
    re_path(r'^$', list_views.home_page, name='home'),
    re_path(r'^lists/', include(list_urls)),
]

esbd2/atividade2/lists/models.py
from django.db import models


class List(models.Model):
    pass


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, on_delete=models.SET_DEFAULT, default=None)
    prioridade = models.TextField(default='')

esbd2/atividade2/lists/views.py
from django.shortcuts import redirect, render
from lists.models import Item, List


def home_page(request):
    return render(request, 'home.html')


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    return render(request, 'list.html', {'list': list_})


def new_list(request):
    list_ = List.objects.create()
    Item.objects.create(text=request.POST['item_text'],
                        list=list_,
                        prioridade=request.POST['prioridades'])

    return redirect(f'/lists/{list_.id}/')


def add_item(request, list_id):
    list_ = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST['item_text'],
                        list=list_,
                        prioridade=request.POST['prioridades'])
    return redirect(f'/lists/{list_.id}/')

esbd2/atividade2/templates/home.html
<html>
	<head>
		<title>priority to-do</title>
	</head>
	<body>
		<h1>priority to-do</h1>
		<form method="POST" action="/lists/new">
			<input name="item_text" id="id_new_item" placeholder="Enter a to-do item" />
            <select name="prioridades" id="prioridade">
              <option value="baixa">baixa</option>
              <option value="alta">alta</option>
            </select>
			{% csrf_token %}
		</form>
	</body>
</html>

esbd2/atividade2/templates/list.html
<html>
	<head>
		<title>To-Do lists</title>
	</head>
	<body>
		<h1>Your To-Do list</h1>
		<form method="POST" action="/lists/{{list.id}}/add_item">
			<input name="item_text" id="id_new_item" placeholder="Enter a to-do item" />
            <select name="prioridades" id="prioridade">
              <option value="baixa">baixa</option>
              <option value="alta">alta</option>
            </select>
			{% csrf_token %}
		</form>
		<table id="id_list_table">
			{% for item in list.item_set.all %}
			<tr><td>{{ forloop.counter }} - {{ item.text }} - prioridade {{ item.prioridade }}</td></tr>
			{% endfor %}
		</table>
	</body>
</html>